### PR TITLE
Update for TB78 & TB91

### PR DESCRIPTION
**Pull request by jobisoft**
This gets you going in TB78 and TB91

### CODE REVIEW

**Comment by peci1** [comment]
Thanks for the help! However, there's still a problem with the options. They do not get applied when a reminder popup is shown (however, on the options pane, they show correctly). I think this was the biggest stopper for me the last time I tried to update WL to the latest version.

**Comment by jobisoft** [comment]
Can you give me steps to reproduce? You opened the options page, while a reminder was shown and wanted the already open reminder to pick up a change you make in the options, for example adding a new value?

**Comment by peci1** [comment]
Nothing like such complicated scenario. Install the addon, check some more options in the options pane. Create a reminder with alert. When the popup shows, only the default options are shown regardless of what I have checked on the options pane.

**Comment by jobisoft** [comment]
It works here. But I wanted to change the prefs anyhow, so I will do that as well.

**Comment by jobisoft** [comment]
This removes usage of common.js (which was a JSM actually), which is what I mentioned in review. Instead, we now use the notifyTools to communicate between legacy parts (the snooze dialog) and the background script, just like we can communicate between WebExtension parts (the options page) and the background script (using runtime messaging).

The updated preference script is using either the notifyTools or runtime messaging to communicate with the background script, where the localStorage handler is managing access to the local storage. I added the localStorage handler as an extra layer (instead of working directly with storage.local), to have proper default value handling.

I have no idea what the mutation observer in the moresnooze.js is doing.

For me this version works in TB91. Can you confirm?

**Comment by jobisoft** [comment]
I just saw, you need to fix the reload button in the options page. What was that supposed to do, reset to defaults?

**Comment by peci1** [comment]
Thanks a lot! I tested the latest changes and the preferences and the rest of the addon now work flawlessly. I also tried restarting TB to see if the preferences are actually stored, and that works, too. The only thing that did not work is migration of preferences. After installation, I only had the default ones selected. Tested on TB 78 on Linux (the only one I have access to now for a few weeks).

Yes, the reload button in options page should reload the default options. Now it ends with an exception.

**Comment by jobisoft** [comment]
Fixed the reload button. So after this is working and passing your tests, I would love to see that in review to be approved for 91. :-)

**Comment by jobisoft** [comment]
> The only thing that did not work is migration of preferences. 

I removed that part, because your current add-on has done the migration already and cleared the legacy pref branch, so there is nothing to migrate anymore.

**Comment by peci1** [comment]
Thanks a lot once more! Now it passes all my local tests, so I'm gonna send the release to ATN.

**Comment by jameshibbard** [comment]
> I have no idea what the mutation observer in the moresnooze.js is doing.

That was me. I added it to account for the case that when one:
- adds an event to the calendar so that the reminder popup gets triggered
- then with the reminder popup open, adds a second event, which also triggers the popup

Then the _Snooze for_ dialog in the second event shows the default snooze time, whereas the _Snooze for_ dialog in the first event, as well as the _Snooze All For_ still show the custom snooze times.

This was discussed here: https://gitter.im/more-snooze/community?at=5dcd1f6cc26e8923c42180fa

I'm sure there's a much better way to solve this, but at the time I was just looking for a way to rebuild the dialog on the fly and that seemed to work.

**Comment by jobisoft** [comment]
That sounds reasonable. If there is no other event to listen to, then a mutation observer is your best option.

**Comment by jameshibbard** [comment]
Ah ok, good to know. Thank you :slightly_smiling_face:

**Pull request merged**
